data:
  source_dir: '/d/Users/eniang.eniang/Desktop/coal_size-detector/data'          # Root directory containing raw images and labels
  images_dir: 'images/train'             # Subdirectory containing images
  labels_dir: 'labels/train'             # Subdirectory containing labels
  processed_dir: 'processed'  # Directory to save processed data
  processed_image: 'processed_image'
  processed_labels: 'processed_labels'
  augmented_dir: 'augmented'  # Directory to save augmented data
  normal_coal_dir: "normal coal flow"
  large_coal_dir: "large pieces"
preprocessing:
  resize: [640, 640]               # Resize images to this size (YOLOv8 default)
